#服务端容器的配置
server:
  port: 8887


#数据库配置
spring:
  datasource:
    username: zhongfucheng
    password: zhong
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ouzicheng?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true

    # formatSQL得这样写
    properties:
      hibernate:
        format_sql: true
# 文件上传的大小
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb

# freemarker配置
  freemarker:
    suffix: .ftl
    request-context-attribute: request
    expose-session-attributes: true
    content-type: text/html
    check-template-location: true
    charset: UTF-8
    cache: false
    template-loader-path: classpath:/templates

# 图片服务器路径
file_path: http://120.78.198.228:8080/fileWeb3

# 图片服务器路径
#file_path: http://localhost:8888


